# Generated by Django 4.1.3 on 2023-01-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bck_accnt', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
